set_property IOSTANDARD LVCMOS33 [get_ports {max[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {max[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {max[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {max[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {max[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {max[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {max[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {max[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {k[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {k[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {k[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {k[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {k[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {k[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {k[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {k[7]}]
set_property PACKAGE_PIN AB20 [get_ports {max[0]}]
set_property PACKAGE_PIN AA21 [get_ports {max[1]}]
set_property PACKAGE_PIN AA20 [get_ports {max[2]}]
set_property PACKAGE_PIN AB18 [get_ports {max[3]}]
set_property PACKAGE_PIN AA19 [get_ports {max[4]}]
set_property PACKAGE_PIN AA18 [get_ports {max[5]}]
set_property PACKAGE_PIN W21 [get_ports {max[6]}]
set_property PACKAGE_PIN W20 [get_ports {max[7]}]
set_property PACKAGE_PIN Y8 [get_ports {k[0]}]
set_property PACKAGE_PIN Y7 [get_ports {k[1]}]
set_property PACKAGE_PIN Y6 [get_ports {k[2]}]
set_property PACKAGE_PIN AA6 [get_ports {k[3]}]
set_property PACKAGE_PIN AA5 [get_ports {k[4]}]
#set_property PACKAGE_PIN AA4 [get_ports {k[5]}]
#set_property PACKAGE_PIN AA3 [get_ports {k[6]}]
#set_property PACKAGE_PIN AA1 [get_ports {k[7]}]
####################################################################################
set_property CFGBVS VCCO [current_design]
####################################################################################
set_property CONFIG_VOLTAGE 3.3 [current_design]
####################################################################################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
####################################################################################
set_property PACKAGE_PIN Y19 [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk_IBUF}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets{clk}]
####################################################################################
####################################################################################